services:
  isaac-lab-base:
    build:
      context: $ISAAC_SCRIPTS_DIR/..
      dockerfile: $ISAAC_SCRIPTS_DIR/Dockerfile
      args:
        - SIM_REPO_PATH=./gen3_isaac_env
      
    volumes:
      - type: bind
        source: $ISAAC_SCRIPTS_DIR/
        target: ${DOCKER_ISAACLAB_PATH}/Isaac-lab-scripts
      # - type: bind
      #   source: $ISAAC_SCRIPTS_DIR/../gen3_isaac_env
      #   target: ${DOCKER_ISAACLAB_PATH}/../sim2real
      
